java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 8080
  environment:
    SERVER_PORT: 8080
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: sscs-tribunals-case-api
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    IDAM_API_URL: ${IDAM_API_URL}
    EMAIL_FROM: "sscs@hmcts.net"
    EMAIL_TO: "sscstest@greencroftconsulting.com"
    EMAIL_SUBJECT: "Your appeal"
    EMAIL_MESSAGE: "Your appeal has been created. Please do not respond to this email"
    ROBOTICS_EMAIL_FROM: "sscs@hmcts.net"
    ROBOTICS_EMAIL_TO: "fake"
    ROBOTICS_EMAIL_SUBJECT: "Robotics Data"
    ROBOTICS_EMAIL_MESSAGE: "Please find attached the robotics json file \nPlease do not respond to this email"
    EMAIL_SERVER_HOST: "mta.reform.hmcts.net"
    EMAIL_SERVER_PORT: "25"
    EMAIL_SMTP_TLS_ENABLED: "true"
    EMAIL_SMTP_SSL_TRUST: "*"
    PDF_API_URL: "http://cmc-pdf-service-aat.service.core-compute-aat.internal"
    SUBSCRIPTIONS_MAC_SECRET: ${SUBSCRIPTIONS_MAC_SECRET}
    CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
    CORE_CASE_DATA_JURISDICTION_ID: "SSCS"
    CORE_CASE_DATA_CASE_TYPE_ID: "Benefit"
    IDAM_S2S_AUTH_TOTP_SECRET: ${IDAM_S2S_AUTH_TOTP_SECRET}
    IDAM_S2S_AUTH: ${IDAM_S2S_AUTH}
    IDAM_S2S_AUTH_MICROSERVICE: ${IDAM_S2S_AUTH_MICROSERVICE}
    IDAM_SSCS_SYSTEMUPDATE_USER: ${IDAM_SSCS_SYSTEMUPDATE_USER}
    IDAM_SSCS_SYSTEMUPDATE_PASSWORD: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD}
    IDAM_OAUTH2_CLIENT_ID: "sscs"
    IDAM_OAUTH2_CLIENT_SECRET: ${IDAM_OAUTH2_CLIENT_SECRET}
    IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
    DOCUMENT_MANAGEMENT_URL: "http://dm-store-aat.service.core-compute-aat.internal"
    MAX_FILE_SIZE: "10MB"
    MAX_REQUEST_SIZE: "10MB"
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single