version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.gorylenko.gradle-git-properties
    versions:
    - 2.3.0
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: net.serenity-bdd:serenity-gradle-plugin
    versions:
    - 2.3.13
    - 2.4.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.0
    - 2.12.1
    - 2.12.2
  - dependency-name: au.com.dius.pact
    versions:
    - 4.1.17
    - 4.2.3
  - dependency-name: org.apache.cxf:cxf-rt-transports-http
    versions:
    - 3.4.3
  - dependency-name: org.apache.cxf:cxf-rt-security
    versions:
    - 3.4.3
  - dependency-name: org.apache.cxf:cxf-rt-rs-client
    versions:
    - 3.4.3
  - dependency-name: org.apache.cxf:cxf-rt-frontend-jaxrs
    versions:
    - 3.4.3
  - dependency-name: org.apache.cxf:cxf-core
    versions:
    - 3.4.3
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-el
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-websocket
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.3
    - 6.1.4
  - dependency-name: uk.gov.hmcts.reform:sscs-common
    versions:
    - 4.2.20
    - 4.2.34
  - dependency-name: org.apache.tomcat:tomcat-annotations-api
    versions:
    - 9.0.40
  - dependency-name: org.jetbrains.kotlin:kotlin-reflect
    versions:
    - 1.4.21-2
    - 1.4.30
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.21-2
    - 1.4.30
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
    - 1.4.30
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-common
    versions:
    - 1.4.21-2
    - 1.4.30
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
    - 1.4.30
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: net.javacrumbs.json-unit:json-unit-fluent
    versions:
    - 2.22.0
